# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagerMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import MainMenu
import DB

class Ui_ManagerMenu(object):

    def setupUi(self, ManagerMenu):
        ManagerMenu.setObjectName("ManagerMenu")
        ManagerMenu.resize(828, 600)
        ManagerMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(ManagerMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logOutButton.setGeometry(QtCore.QRect(50, 480, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.logOutButton.setFont(font)
        self.logOutButton.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.logOutButton.setObjectName("logOutButton")
        self.showUsersButton = QtWidgets.QPushButton(self.centralwidget)
        self.showUsersButton.setGeometry(QtCore.QRect(50, 230, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.showUsersButton.setFont(font)
        self.showUsersButton.setObjectName("showUsersButton")
        self.viewChildResultButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewChildResultButton.setGeometry(QtCore.QRect(480, 230, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.viewChildResultButton.setFont(font)
        self.viewChildResultButton.setObjectName("viewChildResultButton")
        self.viewQuestionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewQuestionsButton.setGeometry(QtCore.QRect(50, 350, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.viewQuestionsButton.setFont(font)
        self.viewQuestionsButton.setObjectName("viewQuestionsButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(130, 60, 601, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.deleteUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteUserButton.setGeometry(QtCore.QRect(480, 350, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.deleteUserButton.setFont(font)
        self.deleteUserButton.setObjectName("deleteUserButton")
        self.viewQuestionsButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.viewQuestionsButton_2.setGeometry(QtCore.QRect(480, 480, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.viewQuestionsButton_2.setFont(font)
        self.viewQuestionsButton_2.setObjectName("viewQuestionsButton_2")
        ManagerMenu.setCentralWidget(self.centralwidget)

        #bttn connect
        self.logOutButton.clicked.connect(self.mainMenu_UI)
        self.logOutButton.clicked.connect(ManagerMenu.close)
        self.logOutButton.clicked.connect(DB.logOut)

        self.retranslateUi(ManagerMenu)
        QtCore.QMetaObject.connectSlotsByName(ManagerMenu)

    def retranslateUi(self, ManagerMenu):
        _translate = QtCore.QCoreApplication.translate
        ManagerMenu.setWindowTitle(_translate("ManagerMenu", "MainWindow"))
        self.logOutButton.setText(_translate("ManagerMenu", "Log Out"))
        self.showUsersButton.setText(_translate("ManagerMenu", "Show Users"))
        self.viewChildResultButton.setText(_translate("ManagerMenu", "View Child result"))
        self.viewQuestionsButton.setText(_translate("ManagerMenu", "View Questions"))
        self.title.setText(_translate("ManagerMenu", "Maneger Menu"))
        self.deleteUserButton.setText(_translate("ManagerMenu", "Delete a User"))
        self.viewQuestionsButton_2.setText(_translate("ManagerMenu", "Allow Parent Reg"))

    def mainMenu_UI(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = MainMenu.Ui_mainMenu()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManagerMenu = QtWidgets.QMainWindow()
    ui = Ui_ManagerMenu()
    ui.setupUi(ManagerMenu)
    ManagerMenu.show()
    sys.exit(app.exec_())
