# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagerMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManagerMenu(object):
    def setupUi(self, ManagerMenu):
        ManagerMenu.setObjectName("ManagerMenu")
        ManagerMenu.resize(743, 501)
        ManagerMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(ManagerMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logOutButton.setGeometry(QtCore.QRect(290, 410, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.logOutButton.setFont(font)
        self.logOutButton.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.logOutButton.setObjectName("logOutButton")
        self.showUsersButton = QtWidgets.QPushButton(self.centralwidget)
        self.showUsersButton.setGeometry(QtCore.QRect(50, 140, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.showUsersButton.setFont(font)
        self.showUsersButton.setObjectName("showUsersButton")
        self.viewChildResultButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewChildResultButton.setGeometry(QtCore.QRect(400, 140, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.viewChildResultButton.setFont(font)
        self.viewChildResultButton.setObjectName("viewChildResultButton")
        self.viewQuestionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewQuestionsButton.setGeometry(QtCore.QRect(410, 290, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.viewQuestionsButton.setFont(font)
        self.viewQuestionsButton.setObjectName("viewQuestionsButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(40, 20, 661, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.deleteUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteUserButton.setGeometry(QtCore.QRect(50, 290, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.deleteUserButton.setFont(font)
        self.deleteUserButton.setObjectName("deleteUserButton")
        ManagerMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManagerMenu)
        QtCore.QMetaObject.connectSlotsByName(ManagerMenu)

    def retranslateUi(self, ManagerMenu):
        _translate = QtCore.QCoreApplication.translate
        ManagerMenu.setWindowTitle(_translate("ManagerMenu", "MainWindow"))
        self.logOutButton.setText(_translate("ManagerMenu", "Log Out"))
        self.showUsersButton.setText(_translate("ManagerMenu", "Show Users"))
        self.viewChildResultButton.setText(_translate("ManagerMenu", "View Child result"))
        self.viewQuestionsButton.setText(_translate("ManagerMenu", "View Questions"))
        self.title.setText(_translate("ManagerMenu", "Maneger Menu"))
        self.deleteUserButton.setText(_translate("ManagerMenu", "Delete a User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManagerMenu = QtWidgets.QMainWindow()
    ui = Ui_ManagerMenu()
    ui.setupUi(ManagerMenu)
    ManagerMenu.show()
    sys.exit(app.exec_())
