pipeline {
    agent {
		docker {
            image 'python:3.7'
        }
	}
    stages {
        stage('Build') {
            steps {
				withEnv(["HOME=${env.WORKSPACE}"]) {
					sh 'python --version'
					sh 'python -m py_compile src/*.py'
					sh 'python src/login/GUI/DB.py'
				}
            }
        }
        stage('Test') {
            steps {
				withEnv(["HOME=${env.WORKSPACE}"]) {
					sh 'python -m pip install pytest'
					sh 'python -m pytest --verbose --junit-xml test-reports/results.xml src/test_db_intergation.py'
                }
            }
        }
    }
}
