
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.7'
                }
            }
            steps {
                sh 'python --version'
                sh 'python -m py_compile src/login/GUI/*.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'python -m unittest src/login/GUI/test_db_intergation.py'
            }
        }
    }
}
